[general]
import = [
  #"dark-mode.toml",
  "light-mode.toml",
  #"themes/king-color-scheme.toml"
  "themes/king-2-color-scheme.toml"
]

[window]
# パディングをウィンドウ全体
dynamic_padding = true
option_as_alt = "Both"

#startup_mode = "Fullscreen"

[font]
normal = { family = "Bizin Gothic NF", style = "Regular" }
size = 18

[keyboard]
bindings = [
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Enter", mods = "Alt", action = "ToggleFullScreen" },
  { key = "-", mods = "Control", chars = "\u001f" },
  { key = "=", mods = "Control", action = "None" }
]
