# Omnisharp
[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs']
hook_source = '''
filetype indent plugin on
augroup Keybind_OmniSharp
  function! s:set_omnisharp_keybind()
    nnoremap <buffer> <F2> <Cmd>OmniSharpRename<CR>
    nnoremap <buffer> <F12> <Cmd>OmniSharpGotoDefinition<CR>
    nnoremap <buffer> <C-F12> <Cmd>OmniSharpFindUsages<CR>
    inoremap <buffer> <C-K><C-K> <Cmd>OmniSharpGetCodeActions<CR>
    nnoremap <buffer> <C-K><C-K> <Cmd>OmniSharpGetCodeActions<CR>
    inoremap <buffer> <C-K><C-D> <Cmd>OmniSharpCodeFormat<CR>
    nnoremap <buffer> <C-K><C-D> <Cmd>OmniSharpCodeFormat<CR>
    inoremap <buffer> <C-K><C-I> <Cmd>OmniSharpDocumentation<CR>
    nnoremap <buffer> <C-K><C-I> <Cmd>OmniSharpDocumentation<CR>
    inoremap <buffer> <C-K><C-J> <Cmd>OmniSharpSignatureHelp<CR>
    nnoremap <buffer> <C-K><C-J> <Cmd>OmniSharpSignatureHelp<CR>
    inoremap <buffer> <Nul> <C-x><C-o>
  endfunction
  autocmd!
  autocmd FileType cs call s:set_omnisharp_keybind()
augroup END
let g:OmniSharp_selector_ui = 'clap'
let g:OmniSharp_highlight_groups = {
\ 'ExtensionMethodName': 'vsExtensionMethodName',
\ 'MethodName': 'vsMethodName',
\ 'ParameterName': 'vsParameterName',
\ 'TypeParameterName': 'vsTypeParameterName',
\ 'PropertyName': 'vsPropertyName',
\ 'FieldName': 'vsFieldName',
\ 'LocalName': 'vsLocalName',
\ 'ConstantName': 'vsConstant',
\ 'InterfaceName': 'vsInterfaceName',
\ 'ClassName': 'vsClassName',
\ 'StructName': 'vsStructName',
\ 'OperatorOverloaded': 'vsOperatorOverloaded',
\ 'ControlKeyword': 'vsControlKeyword',
\ 'Keyword': 'vsKeyword',
\ 'StringLiteral': 'vsString',
\ 'PreprocessorKeyword': 'vsPreprocessor',
\ 'ExcludedCode': 'vsExcluded',
\}
hi Operator ctermfg=250
hi link vsOperatorOverloaded Operator
hi vsMethodName ctermfg=230
hi link vsExtensionMethodName vsMethodName
hi vsTypeParameterName ctermfg=193
hi vsParameterName ctermfg=222
hi vsLocalName ctermfg=252
hi vsOperaterOverloaded ctermfg=7
hi vsControlKeyword ctermfg=219
hi vsKeyword ctermfg=153
hi vsPropertyName ctermfg=254
hi vsFieldName ctermfg=254
hi vsConstant ctermfg=251
hi vsInterfaceName ctermfg=122
hi vsClassName ctermfg=79
hi vsStructName ctermfg=113
hi vsString ctermfg=216
hi vsPreprocessor ctermfg=245
hi link vsExcluded vsPreprocessor
hi Identifier ctermfg=lightgray
hi Comment ctermfg=darkgray
hi link csType vsKeyword
hi link csModifier vsKeyword
hi link csAsync vsKeyword
hi link csConstant vsConstant
hi link csNumber vsConstant
hi link csString vsString
hi link csCharacter vsString
hi link StringLiteral vsString
'''

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['css', 'html', 'less', 'sass', 'scss', 'stylus', 'vim']

